name: Build (Debug)

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  create-release:
    strategy:
      matrix:
        os: [linux, win, osx]
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build ./CLI/CLI.csproj --no-restore --os ${{matrix.os}} --output ./build/${{matrix.os}} --configuration Release
    - name: Test
      run: dotnet test --no-build --verbosity normal
    - name: Upload Build
      uses: actions/upload-artifact@v4
      with:
        name: velvet-beautifier-${{matrix.os}}
        path: ./build/${{matrix.os}}