name: Build (Release)

permissions:
  contents: write

on:
    release:
        types:
            - published
jobs:
  create-release:
    strategy:
      matrix:
        os: [linux, win, osx]
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build ./CLI/CLI.csproj --no-restore --runtime ${{matrix.os}}-x64 --output ./build/${{matrix.os}} --configuration Release
    - name: Test
      run: dotnet test --no-build --verbosity normal
    - name: Create Archive
      run: tar -czvf velvet-beautifier-${{matrix.os}}.zip ./build/${{matrix.os}}/**/*
    - name: Upload Build
      uses: softprops/action-gh-release@v2
      with:
        files: velvet-beautifier-${{matrix.os}}.zip