name: Build (Release)

permissions:
  contents: write

on:
    release:
        types:
            - published
jobs:
  create-release:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    runs-on: ${{matrix.os}}
    defaults:
      run:
        shell: bash

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build ./CLI/CLI.csproj --no-restore --output ./build/${{runner.os}} --configuration Release
    - name: Test
      run: dotnet test --no-build --verbosity normal
    - name: Create Archive
      run: tar -czvf VelvetBeautifier.${{runner.os}}.zip ./build/${{runner.os}}/**/*
    - name: Upload Build
      uses: softprops/action-gh-release@v2
      with:
        name: VelvetBeautifier.${{runner.os}}
        files: VelvetBeautifier.${{runner.os}}.zip